config/routes.rb
Rails.application.routes.draw do
  resources :todos

  resources :practices

  root 'pages#index'
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'getting-started' => 'pages#getting_started', as: :getting_started
  devise_for :users, controllers: { registrations: 'registrations'}

  resources :verses
  resources :kids
  resources :memorizeds
  resources :parents

end

app/models/kid.rb
class Kid < ActiveRecord::Base
  has_many :memorizeds
  belongs_to :parent
  validates_presence_of :name
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]
  before_action :checky_cheese_parent_check, only: [:show]
  before_action :check_logged_in

  def index
    @kids = Kid.all
  end

  def show
    @verses = @kid.memorizeds
    @current = if @verses.last
        @undo = @kid.memorizeds.last
        Verse.find(@verses.max.verse.ref_id + 1)
      else
        Verse.find_by_ref_id(1)
      end
  end

  def new
    @kid = Kid.new
  end

  def edit; end

  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: "#{@kid.name} has begun the journey." }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: "#{@kid.name}, you bless my heart..." }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def checky_cheese_parent_check
    if @kid.parent_id != current_user.parent.id
      redirect_to parent_path(current_user.parent), notice: "You're not a kidnapper, are YOU?!????"
    end
  end

  def set_kid
    @kid = Kid.find(params[:id])
  end

  def kid_params
    params.require(:kid).permit(:parent_id, :name)
  end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.erb
<%= form_for(@kid) do |f| %>
  <% if @kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% @kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :parent_id, value: current_user.parent.id %>
  </div>

  <div class="field">
    <%= f.text_field :name, placeholder: '"Oscar"' %>
  </div>
  <div class="actions">
    <%= f.submit "Add"%>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing Kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kids</h1>

<table>
  <thead>
    <tr>
      <th>Parent</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.parent_id %></td>
        <td><%= kid.name %></td>
        <td><%= link_to 'Show', kid %></td>
        <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
        <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<div class="l-wrapper">
  <h1>Add a Kid</h1>
  <%= render 'form' %>
</div>

app/views/kids/show.html.erb
<div class="l-wrapper">
  <h1><%= @kid.name %></h1>
  <b>Proverbs <%= @current.chapter %>:<%= @current.verse %></b>
  <h2 class='current-verse'><%= @current.text %></h2>

  <%= form_tag("/memorizeds", method: :post) do %>
    <%= hidden_field_tag 'kid_id', @kid.id %>
    <%= hidden_field_tag 'ref_id', @current.ref_id %>
    <%= hidden_field_tag 'verse_id', @current.id %>
    <%= submit_tag("Memorized!") %>
  <% end %>


  <hr>
  <% if @undo %>
    <div>
      <%= link_to 'Undo last Proverb', memorized_path(@undo.id), method: :delete %>
    </div>
  <% end %>
  <b>Completed Proverbs</b>
  <% @verses.each do |v| %>
  <p><b><%= v.verse.verse %></b> <%= v.verse.text %></p>
  <% end %>
</div>