config/routes.rb
Rails.application.routes.draw do
  resources :todos

  resources :practices

  root 'pages#index'
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'getting-started' => 'pages#getting_started', as: :getting_started
  devise_for :users, controllers: { registrations: 'registrations'}

  resources :verses
  resources :kids
  resources :memorizeds
  resources :parents

end

app/views/shared/_footer.html.erb
<footer>
  <div class="l-wrapper">
    <ul>
      <li><%= link_to 'getting started', getting_started_path %></li>
      <li><%= link_to 'about', about_path %></li>
      <li><%= link_to 'contact', contact_path %></li>
    </ul>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div class="logo">
  <%= link_to 'proverbs', root_path %>
</div>
<% unless user_signed_in? %>
  <% unless request.env['PATH_INFO'] =~ /sign_in/ || request.env['PATH_INFO'] =~ /sign_up/%>
    <div class="sign-in-up l-wrapper">
      <ul>
        <li><%= link_to 'sign up', new_user_registration_path %></li>
        <li><%= link_to 'sign in', new_user_session_path %></li>
      </ul>
    </div>
  <% end %>
<% else %>
  <div id='menu-icon'>menu</div>
  <nav id='menu-nav' class='hide'>
      <% unless(params[:controller] == 'parents' && params[:action] == 'new') %>
      <ul>
        <% unless current_user.parent.nil? %>
          <li><%= link_to 'practice', practices_path %></li>
          <% unless current_user.parent.kids.nil? %>
            <% current_user.parent.kids.each do |kid| %>
              <li><%= link_to "#{kid.name}'s path", kid_path(kid) %></li>
            <% end %>
          <% end %>
        <% end %>
        <li><%= link_to 'proverbs', verses_path %></li>
        <li><%= link_to 'todo list', todos_path %></li>
        <li><%= link_to 'new kid', new_kid_path %></li>
        <li><%= link_to 'sign out', destroy_user_session_path, method: "DELETE" %></li>
      </ul>
    <% end %>
  </nav>
<% end %>