config/routes.rb
Rails.application.routes.draw do
  resources :todos

  resources :practices

  root 'pages#index'
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'getting-started' => 'pages#getting_started', as: :getting_started
  devise_for :users, controllers: { registrations: 'registrations'}

  resources :verses
  resources :kids
  resources :memorizeds
  resources :parents

end

app/models/practice.rb
class Practice < ActiveRecord::Base
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]

  # GET /practices
  # GET /practices.json
  def index
    @practice = Practice.order("RANDOM()").first
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit
  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)

    respond_to do |format|
      if @practice.save
        format.html { redirect_to @practice, notice: 'Practice was successfully created.' }
        format.json { render :show, status: :created, location: @practice }
      else
        format.html { render :new }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url, notice: 'Practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      params.require(:practice).permit(:title, :body)
    end
end

app/views/practices/_form.html.erb
<%= form_for(@practice) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/practices/edit.html.erb
<h1>Editing Practice</h1>

<%= render 'form' %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

app/views/practices/index.html.erb
<div class="l-wrapper">
  <% if current_user.parent.kids.empty? %>
    <p><%= link_to "Add your first born", new_kid_path %></p>
  <% end %>
  <a href="" title="">try a different practice</a>
  <h3><%= @practice.title %></h3>
  <p><%= @practice.body %></p>
  <% if @practice.example.present? %>
    <b>example</b>
    <p><%= @practice.example %></p>
  <% end %>
</div>

app/views/practices/new.html.erb
<h1>New Practice</h1>

<%= render 'form' %>

<%= link_to 'Back', practices_path %>

app/views/practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @practice.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @practice.body %>
</p>

<%= link_to 'Edit', edit_practice_path(@practice) %> |
<%= link_to 'Back', practices_path %>